/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;

import java.util.ArrayList;
import java.util.Date;

import javax.swing.table.DefaultTableModel;
import model.HopDong.ModelHopDong;
import model.KhachThue.ModelKhachThue;
import repository.HopDong.repositoryHopDong;
import repository.KhachThue.repositoriesKhachThue;
import view.component.message.MessageFrame;

/**
 *
 * @author X1
 */
public class QlyHopDong extends javax.swing.JPanel {
    
    private repository.KhachThue.repositoriesKhachThue rpKT = new repositoriesKhachThue();
    private repository.HopDong.repositoryHopDong rpHD = new repositoryHopDong();
    private DefaultTableModel mol = new DefaultTableModel();
    private int index = -1;
    private MessageFrame mesg;

    /**
     * Creates new form QlyHopDong
     */
    public QlyHopDong() {
        initComponents();
        fillTable(rpHD.getAll(0));
        fillCbbMaPT(rpHD.getCbbMaPhong());
        fillCbbMaKT(rpHD.getCbbKT());
        tblHopDong.fixTable(jScrollPane5);
        tblKhachThue.fixTable(jScrollPane2);
        txtDieuKhoan.setLineWrap(true);
        txtDieuKhoan.setWrapStyleWord(true);
        this.disPlay(0);
    }
    
    public void fillTable(ArrayList<model.HopDong.ModelHopDong> list) {
        mol = (DefaultTableModel) tblHopDong.getModel();
        mol.setNumRows(0);
        cbbMaHopDong.removeAllItems();
        for (ModelHopDong x : list) {
            mol.addRow(x.toDataRow());
            cbbMaHopDong.addItem(x.getMaHD());
            
        }
        
    }
    
    public void fillCbbMaPT(ArrayList<model.HopDong.ModelHopDong> list) {
        cbbMaPhongTro.removeAllItems();
        for (ModelHopDong x : list) {
            cbbMaPhongTro.addItem(x.getMaPT());
        }
        
    }
    
    public void fillCbbMaKT(ArrayList<model.HopDong.ModelHopDong> list) {
        cbbKhachThue.removeAllItems();
        for (ModelHopDong x : list) {
            cbbKhachThue.addItem(x.getMaKT());
        }
        
    }
    
    public void fillTablePhu(ArrayList<model.KhachThue.ModelKhachThue> list) {
        mol = (DefaultTableModel) tblKhachThue.getModel();
        mol.setNumRows(0);
        for (ModelKhachThue x : list) {
            mol.addRow(x.bangPhu());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        table1 = new view.component.table.Table();
        jPasswordField1 = new javax.swing.JPasswordField();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new view.component.button.Button();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtSoLuongNguoi = new view.component.textfield.TextField();
        txtNgayBatDau = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtNgayKetThuc = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtThoiHan = new view.component.textfield.TextField();
        txtGiaPhong = new view.component.textfield.TextField();
        txtTienCoc = new view.component.textfield.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDieuKhoan = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rdoConHan = new javax.swing.JRadioButton();
        rdoHetHan = new javax.swing.JRadioButton();
        btnThem = new view.component.button.Button();
        btnCapNhat = new view.component.button.Button();
        btnLamMoi = new view.component.button.Button();
        cbbMaHopDong = new view.component.combobox.Combobox();
        cbbMaPhongTro = new view.component.combobox.Combobox();
        cbbKhachThue = new view.component.combobox.Combobox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhachThue = new view.component.table.Table();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblHopDong = new view.component.table.Table();
        cbbBoLoc = new view.component.combobox.Combobox();

        jLabel1.setText("jLabel1");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(table1);

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(255, 255, 255));

        btnTimKiem.setBackground(new java.awt.Color(204, 255, 204));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("Quản lý khách thuê/Hợp đồng");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtSoLuongNguoi.setLabelText("Số lượng người");

        txtNgayBatDau.setBackground(new java.awt.Color(255, 255, 255));
        txtNgayBatDau.setDateFormatString("dd-MM-yyyy");

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Ngày bắt đầu");

        txtNgayKetThuc.setBackground(new java.awt.Color(255, 255, 255));
        txtNgayKetThuc.setDateFormatString("dd-MM-yyyy");

        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Ngày kết thúc");

        txtThoiHan.setLabelText("Thời hạn");

        txtGiaPhong.setEditable(false);
        txtGiaPhong.setLabelText("Giá phòng");

        txtTienCoc.setLabelText("Số tiền cọc");

        txtDieuKhoan.setColumns(20);
        txtDieuKhoan.setRows(5);
        jScrollPane1.setViewportView(txtDieuKhoan);

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Điều khoản");

        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Trạng thái");

        buttonGroup1.add(rdoConHan);
        rdoConHan.setText("Còn hạn");

        buttonGroup1.add(rdoHetHan);
        rdoHetHan.setText("Hết hạn");

        btnThem.setBackground(new java.awt.Color(102, 255, 102));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(204, 204, 204));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(204, 255, 255));
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        cbbMaHopDong.setLabeText("ID Hợp đồng");

        cbbMaPhongTro.setLabeText("Mã phòng");
        cbbMaPhongTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbMaPhongTroMouseClicked(evt);
            }
        });
        cbbMaPhongTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaPhongTroActionPerformed(evt);
            }
        });

        cbbKhachThue.setLabeText("Mã khách");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addComponent(txtNgayBatDau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbbKhachThue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbMaPhongTro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbMaHopDong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSoLuongNguoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtThoiHan, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txtGiaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTienCoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCapNhat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoConHan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoHetHan)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbMaHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThoiHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbMaPhongTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbKhachThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoLuongNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(3, 3, 3)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(rdoConHan)
                                    .addComponent(rdoHetHan))
                                .addGap(17, 17, 17))))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Chi tiết Khách thuê trong phòng");

        tblKhachThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khách", "Họ Tên", "Giới Tính", "Điện thoại", "CCCD"
            }
        ));
        jScrollPane2.setViewportView(tblKhachThue);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jLabel10.setText("Bộ lọc");

        tblHopDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã hợp đồng", "Mã phòng", "Mã khách", "Số người", "Ngày bắt đầu", "Ngày kết thúc", "Thời hạn", "Giá phòng", "Số tiền cọc", "Điều khoản", "Trạng thái"
            }
        ));
        tblHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHopDongMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblHopDong);

        cbbBoLoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "còn hạn", "hết hạn" }));
        cbbBoLoc.setLabeText("");
        cbbBoLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbBoLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbBoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 830, Short.MAX_VALUE))))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbbBoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        mesg = new MessageFrame();
        int tt = 1;
        
        if (readForm() != null) {
            if (readForm().getMaPT().equals(rpHD.check(cbbMaPhongTro.getSelectedItem().toString()))) {
                mesg.showMessage("error", "Phòng " + cbbMaPhongTro.getSelectedItem().toString() + " Đang còn hạn hợp đồng");
                
            } else {
                if (rpHD.them(readForm()) > 0) {
                    mesg.showMessage("success", "Thêm thành công");
                    fillTable(rpHD.getAll(0));
                } else {
                    mesg.showMessage("error", "Thêm thất bại");
                }
            }
            
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        fillCbbMaPT(rpHD.getCbbMaPhong());
        fillCbbMaKT(rpHD.getCbbKT());
        cbbMaPhongTro.setSelectedItem(0);
        txtSoLuongNguoi.setText("");
        txtNgayBatDau.setDate(null);
        txtNgayKetThuc.setDate(null);
        txtThoiHan.setText("");
        txtGiaPhong.setText("");
        txtTienCoc.setText("");
        txtDieuKhoan.setText("");
        txtTimKiem.setText("");
        fillTable(rpHD.getAll(0));
        fillTablePhu(rpKT.timKiem("null", 0));

    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        mesg = new MessageFrame();
        if (readForm() != null) {
            if (rpHD.sua(readForm()) > 0) {
                mesg.showMessage("success", "Cập nhật thành công");
                fillTable(rpHD.getAll(0));
            } else {
                mesg.showMessage("error", "Cập nhật thất bại");
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        int tt = 1;
        if (cbbBoLoc.getSelectedItem().equals("còn hạn")) {
            tt = 0;
        }
        this.fillTable(rpHD.TimKiem(txtTimKiem.getText(), tt));
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblHopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHopDongMouseClicked
        // TODO add your handling code here:
        index = tblHopDong.getSelectedRow();
        this.disPlay(index);
    }//GEN-LAST:event_tblHopDongMouseClicked

    private void cbbBoLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbBoLocActionPerformed
        // TODO add your handling code here:
        if (cbbBoLoc.getSelectedItem().equals("còn hạn")) {
            this.fillTable(rpHD.getAll(0));
            
        } else {
            this.fillTable(rpHD.getAll(1));
        }
    }//GEN-LAST:event_cbbBoLocActionPerformed

    private void cbbMaPhongTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaPhongTroActionPerformed
        // TODO add your handling code here:
        if (cbbMaPhongTro.getSelectedItem() != null) {
            float gia= rpHD.getGiaPhong(cbbMaPhongTro.getSelectedItem().toString());
            txtGiaPhong.setText(gia +"");
        }
        
    }//GEN-LAST:event_cbbMaPhongTroActionPerformed

    private void cbbMaPhongTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbMaPhongTroMouseClicked
        // TODO add your handling code here:
//        float gia= rpHD.getGiaPhong(cbbMaPhongTro.getSelectedItem().toString());
//        txtGiaPhong.setText(gia +"");
    }//GEN-LAST:event_cbbMaPhongTroMouseClicked
    
    public void disPlay(int index){
         cbbMaHopDong.setSelectedItem(tblHopDong.getValueAt(index, 0));
        cbbMaPhongTro.setSelectedItem(tblHopDong.getValueAt(index, 1));
        cbbKhachThue.setSelectedItem(tblHopDong.getValueAt(index, 2));
        txtSoLuongNguoi.setText(tblHopDong.getValueAt(index, 3).toString());
        txtNgayBatDau.setDate((Date) tblHopDong.getValueAt(index, 4));
        txtNgayKetThuc.setDate((Date) tblHopDong.getValueAt(index, 5));
        txtThoiHan.setText(tblHopDong.getValueAt(index, 6).toString());
        txtGiaPhong.setText(tblHopDong.getValueAt(index, 7).toString());
        txtTienCoc.setText(tblHopDong.getValueAt(index, 8).toString());
        txtDieuKhoan.setText(tblHopDong.getValueAt(index, 9).toString());
        if (tblHopDong.getValueAt(index, 10).toString().equalsIgnoreCase("còn hạn")) {
            rdoConHan.setSelected(true);
        } else {
            rdoHetHan.setSelected(true);
        }
        
        int tt;
        if (cbbBoLoc.getSelectedItem().toString().equalsIgnoreCase("còn hạn")) {
            tt = 0;
        } else {
            tt = 1;
        }
        fillTablePhu(rpKT.timKiem(cbbMaPhongTro.getSelectedItem().toString(), tt));
    }
    
    public model.HopDong.ModelHopDong readForm() {
        mesg = new MessageFrame();
        String maHD, maPT, maKT, dieuKhoan;
        int soNguoi;
        int thoiHan;
        Date ngayBD, ngayKT;
        float giaPhong, tienCoc;
        boolean trangThai;
        
        maHD = cbbMaHopDong.getSelectedItem().toString();
        maPT = cbbMaPhongTro.getSelectedItem().toString();
        maKT = cbbKhachThue.getSelectedItem().toString();
        
        ngayBD = txtNgayBatDau.getDate();
        ngayKT = txtNgayKetThuc.getDate();
        
        dieuKhoan = txtDieuKhoan.getText();
        if (rdoConHan.isSelected()) {
            trangThai = false;
        } else {
            trangThai = true;
        }
        
        if (txtSoLuongNguoi.getText().equalsIgnoreCase("")) {
            mesg.showMessage("error", "chưa nhập số lượng người");
            txtSoLuongNguoi.requestFocus();
            return null;
        }
        if (ngayBD.equals("")) {
            mesg.showMessage("error", "chưa nhập ngày bắt đầu");
            txtNgayBatDau.requestFocus();
            return null;
        }
        if (ngayKT.equals("")) {
            mesg.showMessage("error", "chưa nhập ngày kết thúc");
            txtNgayKetThuc.requestFocus();
            return null;
        }
        if (txtThoiHan.getText().equalsIgnoreCase("")) {
            mesg.showMessage("error", "chưa nhập thời hạn");
            txtThoiHan.requestFocus();
            return null;
        }
        if (txtGiaPhong.getText().equals("")) {
            mesg.showMessage("error", "chưa nhập giá phòng");
            txtGiaPhong.requestFocus();
            return null;
        }
        if (txtTienCoc.getText().equals("")) {
            mesg.showMessage("error", "chưa nhập số tiền cọc");
            txtTienCoc.requestFocus();
            return null;
        }
        if (dieuKhoan.isEmpty()) {
            mesg.showMessage("error", "chưa nhập điều khoản");
            txtDieuKhoan.requestFocus();
            return null;
        }
        if (rdoConHan.isSelected() == false && rdoHetHan.isSelected() == false) {
            mesg.showMessage("error", "chưa lựa chọn trạng thái");
            return null;
        }
        soNguoi = Integer.parseInt(txtSoLuongNguoi.getText());
        thoiHan = Integer.parseInt(txtThoiHan.getText());
        giaPhong = Float.parseFloat(txtGiaPhong.getText());
        tienCoc = Float.parseFloat(txtTienCoc.getText());
        
        return new model.HopDong.ModelHopDong(maHD, maPT, maKT, soNguoi, ngayBD, ngayKT, thoiHan, giaPhong, tienCoc, dieuKhoan, trangThai);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.component.button.Button btnCapNhat;
    private view.component.button.Button btnLamMoi;
    private view.component.button.Button btnThem;
    private view.component.button.Button btnTimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private view.component.combobox.Combobox cbbBoLoc;
    private view.component.combobox.Combobox cbbKhachThue;
    private view.component.combobox.Combobox cbbMaHopDong;
    private view.component.combobox.Combobox cbbMaPhongTro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton rdoConHan;
    private javax.swing.JRadioButton rdoHetHan;
    private view.component.table.Table table1;
    private view.component.table.Table tblHopDong;
    private view.component.table.Table tblKhachThue;
    private javax.swing.JTextArea txtDieuKhoan;
    private view.component.textfield.TextField txtGiaPhong;
    private com.toedter.calendar.JDateChooser txtNgayBatDau;
    private com.toedter.calendar.JDateChooser txtNgayKetThuc;
    private view.component.textfield.TextField txtSoLuongNguoi;
    private view.component.textfield.TextField txtThoiHan;
    private view.component.textfield.TextField txtTienCoc;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
