/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.panel;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.NhanVien.Model_Luong;
import repository.NhanVien.repoDiemDanh;
import repository.NhanVien.repo_Luong;
import view.component.message.MessageFrame;
/**
 *
 * @author BOSS
 */
public class QlyLuong extends javax.swing.JPanel {
    private repo_Luong  rpLuong = new repo_Luong();
    private DefaultTableModel TableLuong = new DefaultTableModel();
    private int i = -1;
    private repoDiemDanh rpDD = new repoDiemDanh();
    private MessageFrame mesF = new MessageFrame();
    // Biến phân trang
    private int currentPage = 1;
    private final int rowsPerPage = 9; // Số hàng mỗi trang
    private int totalRows;
    private int totalPages;
    /**
     * Creates new form QlyLuong
     */
    public QlyLuong() {
        initComponents();
        fillTable(rpLuong.getAllLuong());
        SearchLuong();
    }
    private void fillTable(ArrayList<Model_Luong> list) {
        TableLuong = (DefaultTableModel) tbl_Luong.getModel();
        totalRows = list.size();
        totalPages = (totalRows + rowsPerPage - 1) / rowsPerPage; // Tính tổng số trang
        int start = (currentPage - 1) * rowsPerPage;
        int end = Math.min(start + rowsPerPage, totalRows);
    TableLuong.setRowCount(0);
    AtomicInteger index = new AtomicInteger(1);
    DecimalFormat formatter = new DecimalFormat("#,###,###");
    // Get attendance data from database
    list.forEach(s -> {
        // Định dạng lương với dấu phân cách hàng nghìn và thêm "Đ" ở cuối
        String formattedLuong = formatter.format(s.getLuongThang()) + " Đ";

        TableLuong.addRow(new Object[]{
            index.getAndIncrement(), s.getMaLuong(), s.getMaNV(), s.getThang(), s.getNam(), s.getSoNgayDiLam(), formattedLuong,s.getHoTen()
        });
    });
    // Cập nhật nhãn trang hiện tại
        jLabel1.setText(String.valueOf(currentPage));
        jLabel3.setText(String.valueOf(totalPages));
    }
    private void SearchLuong() {
        txt_TimKiemLuong.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                timKiemNgayThang();
            }
            
            @Override
            public void removeUpdate(DocumentEvent e) {
                timKiemNgayThang();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                timKiemNgayThang();
            }
            
        });
    }
     private void timKiemNgayThang() {
        String timkiem = txt_TimKiemLuong.getText().trim();
        fillTable(rpLuong.search(timkiem));
    }
//    private int parseIntOrDefault(String value, int defaultValue) {
//    try {
//        return Integer.parseInt(value);
//    } catch (NumberFormatException e) {
//        return defaultValue;
//    }
//}
//     public double tinhLuong(int soNgayDiLam) {
//    final double LUONG_MOI_NGAY = 200000; // Lương mỗi ngày
//    return soNgayDiLam * LUONG_MOI_NGAY;
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_TimKiemLuong = new view.component.textfield.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Luong = new view.component.table.Table();
        btn_Xoa = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_Next = new view.component.button.MyButton();
        btn_Prev = new view.component.button.MyButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txt_TimKiemLuong.setLabelText("Tìm kiếm theo tháng, năm");
        txt_TimKiemLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TimKiemLuongActionPerformed(evt);
            }
        });

        tbl_Luong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã lương", "Mã nhân viên", "Tháng", "năm", "Số ngày đi làm", "Lương", "Tên Nhân Viên"
            }
        ));
        jScrollPane1.setViewportView(tbl_Luong);
        if (tbl_Luong.getColumnModel().getColumnCount() > 0) {
            tbl_Luong.getColumnModel().getColumn(2).setResizable(false);
            tbl_Luong.getColumnModel().getColumn(6).setResizable(false);
            tbl_Luong.getColumnModel().getColumn(7).setResizable(false);
        }

        btn_Xoa.setBackground(new java.awt.Color(102, 255, 204));
        btn_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 204));
        jButton2.setText("Xắp xếp");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_next_24px.png"))); // NOI18N
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });

        btn_Prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_previous_24px.png"))); // NOI18N
        btn_Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrevActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("1");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setText("/");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_TimKiemLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_Xoa)
                .addGap(33, 33, 33)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(471, 471, 471))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TimKiemLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Xoa)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Prev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Next, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
       int selectedRow = tbl_Luong.getSelectedRow();
    if (selectedRow != -1) {
        int maLuong = Integer.parseInt(tbl_Luong.getValueAt(selectedRow, 1).toString());

        int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (rpLuong.delete(maLuong) > 0) {
                mesF.showMessage("success", "Xóa thành công");
                fillTable(rpLuong.getAllLuong());
            } else {
                mesF.showMessage("error", "Xóa thất bại");
            }
        }
    } else {
        mesF.showMessage("error", "Chưa chọn dòng nào");
    }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fillTable(rpLuong.xapXepLuong());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_TimKiemLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TimKiemLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TimKiemLuongActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        // TODO add your handling code here:
       if (currentPage < totalPages) {
            currentPage++;
            fillTable(rpLuong.getAllLuong());
        }
    }//GEN-LAST:event_btn_NextActionPerformed

    private void btn_PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrevActionPerformed
        // TODO add your handling code here:
        if (currentPage > 1) {
            currentPage--;
            fillTable(rpLuong.getAllLuong());
        }
    }//GEN-LAST:event_btn_PrevActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.component.button.MyButton btn_Next;
    private view.component.button.MyButton btn_Prev;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private view.component.table.Table tbl_Luong;
    private view.component.textfield.TextField txt_TimKiemLuong;
    // End of variables declaration//GEN-END:variables

}
